language: python

dist: xenial

cache: false

sudo: false

python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

before_install:
  - sudo apt-get update
  - pip install -r requirements.txt
  - pip install --upgrade -r requirements.txt
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt

install:
  - python setup.py build_ext --inplace --force --define CYTHON_TRACE_NOGIL

script:
  - coverage run -m py.test panels
  - coverage report

after_success:
  - coveralls

notifications:
  email:
    on_success: change
    on_failure: change

